### ISSUE TITLE
com querySelector

### ISSUE THREAD

**Issue by fontez** [Rocketseat/starter-javascript-exercicios#5]
pensei a nivel de performance. qual seria o mais rapido?
`var btnElement = document.querySelector('#new');`
ou
`var btnElement = document.getElementById('new');`

https://github.com/Rocketseat/starter-javascript-exercicios/blob/3f10ae3a7ae5cebf1ddcc68b9cd2af10dd67b212/M%C3%B3dulo%2002/02.html#L14

**Comment by diego3g** [comment]
Indiferente, a nível de realizar milhões de chamadas talvez daí exista algum tipo de diferença, mas no dia-a-dia não existe diferença.
